version: '3'

services:
  app:
    build: .docker
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig
    working_dir: /app
    environment:
      HOST: 0.0.0.0
